travis:
  secure:
    BINSTAR_TOKEN: sr+NlSTPcOXK+CwBV6o3UCWyAaDIsiweO9VjnjwGjbT3i2mMBVUPxFi3OAtouJC8bOVKM1ydp7/6yzPOdGqIFw1K1VP+B7/LIrhjY1Mp69YNTOljYTXQfHEA/a0mNXhbm1p5h7EdibXWgPp1CHV0AikzLnaox9lrFk/9EHmPnEdzFJ1h5fl+wd827HUfsosZ9iCkTLo3yLPgXRSmtsVY4mqt1VFwHdBdkuh7yvJScshsd+Cmly3OYW3qy2jQ6nDk3e3vreUhjEJW8cFyDconL5cQz+fZP5y8fn2KkUONHVFO+EQIjANly9uRRQ6W1VnsfaaQzH6QLzXGd+kUouiiohxoPI+MZBv2u2DSeWSufcLViHnv2B8a0Zo3x8TT7917NJEzdeqNKu3/BsUyrUz0Zxrgjuz0Z6Zt14huXVLNG1ehpI0nY4r1iM5YyHE6IZovw8zCQof20kGk95nSmy16HuOXJVDbh7FO6H1joIR1Nu+KtwcjHr04B4wKBjOMR7GkDSye4u9fIxByRKqGw4izURucCa06UOPVjr68yZPt+LQa1dD2ZVLkf673e07Tr1iNmRhJEeJKt9rjJ5jhEr2r/yKtPFPRNvXglZSZOYuZrGyvPMb3Cgj8qwJos6qM7bNTsVbOE+UCr19RiCpzzwHC7uhGum8dmQS4SXOuXVRwato=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
