travis:
  secure:
    BINSTAR_TOKEN: 7N5Q7PviHFW/RqTh+SYgTWyvioBPnGWb+qtW8vFUmwEhE38IcufEXif+iNXmauLBDfK7YMFZX8HP7LORcDCF5WO+ELTzOPV9EqEO7Hd2jqSUzdC77E3M1WoBJwThByRO6GYTqhQ+Ice0xn8CQNvCx7oSVkgs0Z3azFmIDWD0dkwJxNbWFHRppG7ejskJgpHGZHJT2qJ8l0xerrK53TDizbk1ldim/2aFthHdQKACYJiFAHJ7sVF1zpZIV+vzfvjxws1NDUQ6g8E+9UxcL6URI1p3g9YNhcgs8ggKnY6zXuaDc9Vjs1F9v0FGNKff4cj7SgrhstdnYVYtlu02g49rO5nZ/wOFraBxlSrKGBESvmQ/kHpqx6XMiw1B1LZdNXDSwMPO7Ub0uWioZxI7qfhuoat/qWIpy4cWmqWswtrZPqs/h77rKi4EGbuJ4419RT1Z1tMqeagFenbAn/ibXmB1Nl5B/npaumemo9MWPu6M17jJ29XvPvIlodIczH+Nzwi/yDl8eIO/zK2eVPW57xhOHm5I1qZ2Yq9KayHCV9hMDZIazOrV4jdgsFRPBE871K2Rn44jVBopOxs9C8NvXHl1Ysr9UkhG/mNvuAgrGQPDGH34f3wRuzxFVVq8jhCBfzOmGpWUnwaQ9mW5mo9g8G2VfuCdN+n9WkLSzPB8wt/Kw7A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
